@echo off
REM CyberPatchMaker Patch Application Script
REM Generated by CyberPatchMaker GUI
REM

title CyberPatchMaker - Applying Patch

echo ========================================
echo CyberPatchMaker - Patch Application
echo ========================================
echo.
echo This script will apply the patch to your installation.
echo.
pause

echo.
echo Applying patch...
echo.

applier.exe --patch "1.0.0-to-1.0.1.patch" --current-dir "%~dp0"

if %ERRORLEVEL% EQU 0 (
    echo.
    echo ========================================
    echo PATCH APPLIED SUCCESSFULLY!
    echo ========================================
    echo.
    echo Your installation has been updated.
    echo.
) else (
    echo.
    echo ========================================
    echo PATCH APPLICATION FAILED!
    echo ========================================
    echo.
    echo Error code: %ERRORLEVEL%
    echo.
    echo Please check the error messages above.
    echo If verification failed, your installation may have been modified.
    echo If backup was enabled, you can restore from the .backup folder.
    echo.
)

echo.
pause
